// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/containers": {
            "get": {
                "description": "get all container list",
                "tags": [
                    "containers"
                ],
                "summary": "get container list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "create a new container",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "Create a container",
                "parameters": [
                    {
                        "description": "Container Spec",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/container.CreateContainerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/containers/{containerId}": {
            "get": {
                "description": "get an exitsting container info",
                "tags": [
                    "containers"
                ],
                "summary": "get container info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container ID",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/containers/{containerId}/actions/delete": {
            "delete": {
                "description": "delete an exitsting container",
                "tags": [
                    "containers"
                ],
                "summary": "delete a container",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container ID",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/containers/{containerId}/actions/exec": {
            "post": {
                "description": "execute command inside an exitsting container",
                "tags": [
                    "containers"
                ],
                "summary": "exec a container",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container ID",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Execute Options",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/container.ExecContainerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/containers/{containerId}/actions/start": {
            "post": {
                "description": "start an exitsting container",
                "tags": [
                    "containers"
                ],
                "summary": "start a container",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container ID",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Start Options",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/container.StartContainerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/containers/{containerId}/actions/stop": {
            "post": {
                "description": "stop an exitsting container",
                "tags": [
                    "containers"
                ],
                "summary": "stop a container",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container ID",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/containers/{containerId}/log": {
            "get": {
                "description": "get container log",
                "tags": [
                    "containers"
                ],
                "summary": "get container log",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container ID",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/hooks/droplet": {
            "post": {
                "description": "apply hook from droplet",
                "tags": [
                    "hooks"
                ],
                "summary": "apply hook",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/images": {
            "get": {
                "description": "get image list in local storage",
                "tags": [
                    "image"
                ],
                "summary": "get image list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "pull image from registry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "pull image",
                "parameters": [
                    {
                        "description": "Target Image",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/image.PullImageRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "remove image from local",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "remove image",
                "parameters": [
                    {
                        "description": "Target Image",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/image.RemoveImageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/policies": {
            "get": {
                "description": "get policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policy"
                ],
                "summary": "get policy list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chain Name",
                        "name": "chainName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add new policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policy"
                ],
                "summary": "Add policy",
                "parameters": [
                    {
                        "description": "policy parameter",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/policy.AddPolicyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/policies/commit": {
            "post": {
                "description": "commit all policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policy"
                ],
                "summary": "commit policy",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/policies/ns/mode": {
            "post": {
                "description": "change north-south mode",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policy"
                ],
                "summary": "change north-south mode",
                "parameters": [
                    {
                        "description": "mode",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/policy.ChangeNSModeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/policies/revert": {
            "post": {
                "description": "revert policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policy"
                ],
                "summary": "revert policy",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/policies/{policyId}": {
            "delete": {
                "description": "remove an existing policy",
                "tags": [
                    "Policy"
                ],
                "summary": "remove a policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Policy ID",
                        "name": "policyId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "container.CreateContainerRequest": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "/bin/sh",
                        "-c",
                        "echo hello; sleep 60"
                    ]
                },
                "env": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "image": {
                    "type": "string",
                    "example": "alpine:latest"
                },
                "mount": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "/host/dir:/container/dir",
                        "/src:/dst"
                    ]
                },
                "name": {
                    "type": "string",
                    "example": "my-container"
                },
                "network": {
                    "type": "string",
                    "example": "raind0"
                },
                "port": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "8080:80",
                        "4443:443"
                    ]
                },
                "tty": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "container.ExecContainerRequest": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "/bin/sh",
                        "-c",
                        "echo hello"
                    ]
                },
                "tty": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "container.StartContainerRequest": {
            "type": "object",
            "properties": {
                "tty": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "image.PullImageRequest": {
            "type": "object",
            "properties": {
                "arch": {
                    "type": "string",
                    "example": "arm64"
                },
                "image": {
                    "type": "string",
                    "example": "alpine:latest"
                },
                "os": {
                    "type": "string",
                    "example": "linux"
                }
            }
        },
        "image.RemoveImageRequest": {
            "type": "object",
            "properties": {
                "image": {
                    "type": "string",
                    "example": "alpine:latest"
                }
            }
        },
        "policy.AddPolicyRequest": {
            "type": "object",
            "properties": {
                "chain": {
                    "type": "string",
                    "example": "RAIND-EW"
                },
                "comment": {
                    "type": "string",
                    "example": "allow https traffic"
                },
                "dest": {
                    "type": "string",
                    "example": "dst-container-name"
                },
                "dport": {
                    "type": "integer",
                    "example": 443
                },
                "protocol": {
                    "type": "string",
                    "example": "tcp"
                },
                "source": {
                    "type": "string",
                    "example": "src-container-name"
                }
            }
        },
        "policy.ChangeNSModeRequest": {
            "type": "object",
            "properties": {
                "mode": {
                    "type": "string",
                    "example": "enforce"
                }
            }
        },
        "utils.ApiResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "description": "success | fail",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
