// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/containers": {
            "post": {
                "description": "create a new container",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "Create a container",
                "parameters": [
                    {
                        "description": "Container Spec",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.CreateContainerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/containers/{containerId}/actions/delete": {
            "delete": {
                "description": "delete an exitsting container",
                "tags": [
                    "containers"
                ],
                "summary": "delete a container",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container ID",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/containers/{containerId}/actions/exec": {
            "post": {
                "description": "execute command inside an exitsting container",
                "tags": [
                    "containers"
                ],
                "summary": "exec a container",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container ID",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Execute Options",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.ExecContainerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/containers/{containerId}/actions/start": {
            "post": {
                "description": "start an exitsting container",
                "tags": [
                    "containers"
                ],
                "summary": "start a container",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container ID",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Start Options",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.StartContainerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/containers/{containerId}/actions/stop": {
            "post": {
                "description": "stop an exitsting container",
                "tags": [
                    "containers"
                ],
                "summary": "stop a container",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container ID",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/hooks/droplet": {
            "post": {
                "description": "apply hook from droplet",
                "tags": [
                    "Hooks"
                ],
                "summary": "apply hook",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.ApiResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.ApiResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "description": "success | fail",
                    "type": "string"
                }
            }
        },
        "http.CreateContainerRequest": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "'/bin/sh'",
                        "'-c'",
                        "'echo hello; sleep 60'"
                    ]
                },
                "image": {
                    "type": "string",
                    "example": "alpine"
                }
            }
        },
        "http.ExecContainerRequest": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "'/bin/sh'",
                        "'-c'",
                        "'echo hello'"
                    ]
                },
                "interactive": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "http.StartContainerRequest": {
            "type": "object",
            "properties": {
                "interactive": {
                    "type": "boolean",
                    "example": true
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
